version: "3"

services:
  mysql-diver-test:
    image: mysql:5.7
    ports:
      - "13307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
  